name: Deploy EcomPulse Api

on:
  workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: "ecompulse-dotnet-api"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore ./EcomPulse.Api/EcomPulse/EcomPulse.csproj

      - name: Build
        run: dotnet build ./EcomPulse.Api/EcomPulse/EcomPulse.csproj --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./EcomPulse.Api/EcomPulse/EcomPulse.csproj --configuration Release --output ./publish
        
      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          publish-profile: ${{secrets.API_PUBLISH_SECRET}}
          package: ./publish
      
