name: Deploy EcomPulse Api

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: "ecompulse-dotnet-api"
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Install dependencies
        run: dotnet restore ./Server/Server.sln

      - name: Build
        run: dotnet build ./Server/Server.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./Server/PresentationLayer/PresentationLayer.csproj --configuration Release  --no-build --output ${{env.AZURE_WEBAPP_PACKAGE_PATH}}
        
      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.API_PUBLISH_SECRET }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
