name: DotnetApiPublish
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
      - name: Restore Dependencies
        uses: dotnet restore ./EcomPulse.Api/EcomPulse.sln
      - name: Build API
        uses: dotnet build --configuration Release ./EcomPulse.Api/EcomPulse.sln
      - name: Publish API
        uses: dotnet build --configuration Release --no-build ./EcomPulse.Api/EcomPulse.sln
