name: Dotnet_Azure_Api_Publish
on:
  workflow_dispatch:
  push:
    branches:
    - main
jobs:
  publish:
    runs-on: ubuntu-lastest
    steps:
    - uses: actions/checkout@v3
  
    - name: Setup .NET
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x  
    - name: Restore
      run: dotnet restore ./EcomPulse.sln
    - name: Build
      run: dotnet build ./EcomPulse.sln --configuration Release
    - name: Publish
      run: dotnet publish ./EcomPulse.sln --configuration Release --no-build
